import type { NextPage } from "next";
import Head from "next/head";
import { ChangeEvent, useState } from "react";

import BooksList from "../components/BooksList";
import getData from "../helpers/fetchBooks";

import BookT from "../typings/Book";

const Home: NextPage = () => {
  const [booksList, setBooksList] = useState<BookT[]>([]);
  const [search, setSearch] = useState("");

  const showAllBooks = async () => {
    setBooksList(await getData("http://localhost:4040/api/books/"));
  };

  const handleChange = async (e: ChangeEvent<HTMLInputElement>) => {
    const { value } = e.target;
    if (value.length < 2) setBooksList([]);
    if (value.length > 2) {
      setBooksList(await getData(`http://localhost:4040/api/books/${value}`));
    }
    setSearch(value);
  };

  return (
    <>
      <Head>
        <title>Books Directory</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/512.png" />
      </Head>

      <main className="h-screen w-screen px-20">
        <section className="">
          <div className="text-center">
            <h1 className="font-['Playfair Display'] my-8 text-4xl font-bold capitalize">
              book directory
            </h1>
            <button
              className="m-auto my-4 block rounded-lg bg-[#553b08] py-2 px-4 text-white"
              onClick={showAllBooks}
            >
              show all books
            </button>
            <input
              type="text"
              value={search}
              placeholder="search for a book..."
              className="w-1/3 rounded-lg p-4"
              onChange={handleChange}
            />
          </div>
          <BooksList booksList={booksList} />
        </section>
      </main>
    </>
  );
};

export default Home;
